USE USERSERVICE;

CREATE TABLE PERMISSION (ID INT AUTO_INCREMENT PRIMARY KEY, PERMISSION_NAME VARCHAR(50) NOT NULL);
CREATE TABLE USERGROUP (ID INT AUTO_INCREMENT PRIMARY KEY, GROUP_NAME VARCHAR(50) NOT NULL);
CREATE TABLE GROUP_PERMISSION (ID INT AUTO_INCREMENT PRIMARY KEY, GROUP_ID INT,FOREIGN KEY(GROUP_ID) REFERENCES USERGROUP(ID), PERMISSION_ID INT,FOREIGN KEY(PERMISSION_ID) REFERENCES PERMISSION(ID));
CREATE TABLE USERS (ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(50) NOT NULL, PASSWORD VARCHAR(1000) NOT NULL, EMAILID VARCHAR(255) NOT NULL, FIRST_NAME VARCHAR(50) NOT NULL,LAST_NAME VARCHAR(50) NOT NULL);
CREATE TABLE GROUP_USERS (ID INT AUTO_INCREMENT PRIMARY KEY, GROUP_ID INT, FOREIGN KEY(GROUP_ID) REFERENCES USERGROUP(ID), USER_ID INT,FOREIGN KEY(USER_ID) REFERENCES USERS(ID));

INSERT INTO PERMISSION (ID,PERMISSION_NAME) VALUES (1, 'CREATE_USER_GROUP');
INSERT INTO USERGROUP (ID, GROUP_NAME) VALUES (1,'SUPERADMIN');
INSERT INTO GROUP_PERMISSION (GROUP_ID,PERMISSION_ID) VALUES (1,1);
INSERT INTO USERS (ID, USERNAME,PASSWORD,EMAILID,FIRST_NAME,LAST_NAME) VALUES (1, 'amaresh','$2a$08$JL293NZPISG33bGbWinZUe/0pIVkOkDEXnh4QpkanFQRknU.mO.Ea','amareswaranvel@gmail.com','Amareswaran','Suriyamurthy');
INSERT INTO GROUP_USERS (GROUP_ID,USER_ID) VALUES (1,1);